language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules


# S: Build Lifecycle
install:
  - npm install

before_script:
 # - npm install -g gulp


script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "misterdong"
  - git config user.email "a895011874@163.com"
  - git add .
  - git commit -m "Update blog"
  - git push --force --quiet "https://${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/misterdong/misterdong.github.io.git